import type { LevelDef } from "@/lib/types";

export const LEVELS: LevelDef[] = [
  {
    id: "L1",
    index: 1,
    chapter: 1,
    name: "唤醒伙伴",
    concept: "角色卡决定它是谁",
    motto: "换张卡，变个它",
    newBlocks: ["persona"],
    shadow: "S3",
    gapCount: 1,
    firstGapSafe: true,
    allowTrial: false,
    autonomy: 5,
    mission: "把一张角色卡放进空槽，点伙伴，看它醒来。",
    wow: "同一个「你是谁」，三张卡三种回答。",
    hook: "灰雾深处，传来一声猫叫。可岛上，没有猫。",
    cutscene: [
      { caption: "灰雾来了。声音，被偷走了。", scene: "fog" },
      { caption: "伙伴躺在沙滩。它忘了自己是谁。", scene: "beach" },
      { caption: "驯养员，用一张卡，唤醒它。", scene: "card" },
    ],
    slots: [
      { id: "trigger", label: "开关", hint: "点一点", accepts: ["trigger-tap"], shadow: "full", prefill: "trigger-tap", locked: true },
      { id: "speech", label: "说话", hint: "气泡", accepts: ["display-speech"], shadow: "full", prefill: "speech", locked: true },
      { id: "opening", label: "开场白", hint: "你是谁？", accepts: ["opening"], shadow: "full", prefill: "opening", locked: true },
      { id: "persona", label: "它是谁", hint: "先放角色卡哦", accepts: ["persona"], shadow: "full", gap: true },
    ],
    pack: ["persona-cat", "persona-dog", "persona-rabbit"],
    quiz: {
      question: "想让伙伴变个样，用什么？",
      options: [
        { id: "a", label: "角色卡", icon: "persona", correct: true },
        { id: "b", label: "百宝箱", icon: "rag" },
        { id: "c", label: "烟花", icon: "firework" },
      ],
      cardIds: ["persona"],
    },
  },
  {
    id: "L2",
    index: 2,
    chapter: 1,
    name: "它开口了",
    concept: "触发器让它开始行动",
    motto: "点一点，就说话",
    newBlocks: ["trigger", "catchphrase"],
    shadow: "S3",
    gapCount: 2,
    firstGapSafe: true,
    allowTrial: false,
    autonomy: 10,
    mission: "给它一句口头禅，再写一句开场白。点它，听它说你的话。",
    wow: "全班同时点伙伴，教室变成口头禅大合唱。",
    hook: "沙滩上出现脚印。圆圆的。不是动物的。",
    cutscene: [
      { caption: "伙伴醒了。可它只会一句。像复读机。", scene: "repeat" },
      { caption: "驯养员，教它说新话。", scene: "card" },
      { caption: "先定暗号：点一点，它就开口。", scene: "light" },
    ],
    slots: [
      { id: "trigger", label: "开关", hint: "点一点", accepts: ["trigger-tap"], shadow: "full", prefill: "trigger-tap", locked: true },
      { id: "persona", label: "它是谁", hint: "角色卡", accepts: ["persona"], shadow: "full", gap: true },
      { id: "speech", label: "说话", hint: "气泡", accepts: ["display-speech"], shadow: "full", prefill: "speech", locked: true },
      { id: "catchphrase", label: "口头禅", hint: "挂嘴边的那句", accepts: ["catchphrase"], shadow: "full", gap: true },
      { id: "opening", label: "开场白", hint: "第一句话", accepts: ["opening"], shadow: "full", gap: true },
    ],
    pack: ["persona-cat", "persona-dog", "persona-rabbit", "catchphrase", "opening"],
    quiz: {
      question: "伙伴怎么开始说话？",
      options: [
        { id: "a", label: "点一点", icon: "trigger", correct: true },
        { id: "b", label: "放烟花", icon: "firework" },
        { id: "c", label: "喂资料", icon: "rag" },
      ],
      cardIds: ["trigger", "catchphrase"],
    },
  },
  {
    id: "L3",
    index: 3,
    chapter: 1,
    name: "喂它记忆",
    concept: "先喂，再问",
    motto: "喂资料，答得妙",
    newBlocks: ["rag"],
    shadow: "S2",
    gapCount: 2,
    firstGapSafe: true,
    allowTrial: true,
    autonomy: 25,
    mission: "先问一次（它会不知道），再把百宝箱和三张资料喂进去，再问。",
    wow: "它不是猜的！它查了我喂的书！",
    hook: "百宝箱底，多出一页记忆。上面写着：灰雾会学人说话。",
    cutscene: [
      { caption: "伙伴想家了。它忘了家。", scene: "home" },
      { caption: "驯养员有百宝箱。喂一口，它想起一口。", scene: "feed" },
      { caption: "先喂，再问。记住顺序。", scene: "badge" },
    ],
    slots: [
      { id: "trigger", label: "开关", hint: "点一点", accepts: ["trigger-tap"], shadow: "full", prefill: "trigger-tap", locked: true },
      { id: "persona", label: "它是谁", hint: "角色卡", accepts: ["persona"], shadow: "outline", gap: true },
      { id: "rag", label: "百宝箱", hint: "从卡包拖百宝箱", accepts: ["rag"], shadow: "outline", gap: true },
      { id: "feed", label: "喂资料", hint: "资料放进箱子", accepts: ["knowledge"], shadow: "outline", gap: true, capacity: 3 },
      { id: "speech", label: "提问", hint: "气泡", accepts: ["display-speech"], shadow: "full", prefill: "speech", locked: true },
    ],
    pack: ["persona-cat", "persona-dog", "persona-rabbit", "rag", "know-echo-loc", "know-echo-food", "know-echo-song"],
    quiz: {
      question: "伙伴怎么知道岛的歌？",
      options: [
        { id: "a", label: "喂了资料", icon: "rag", correct: true },
        { id: "b", label: "它瞎猜", icon: "persona" },
        { id: "c", label: "它做梦", icon: "firework" },
      ],
      cardIds: ["rag"],
    },
  },
  {
    id: "L4",
    index: 4,
    chapter: 1,
    name: "专属记忆",
    concept: "喂什么，答什么",
    motto: "喂什么，答什么",
    newBlocks: ["memory"],
    shadow: "S2",
    gapCount: 3,
    firstGapSafe: false,
    allowTrial: true,
    autonomy: 40,
    mission: "在混着的资料里，挑出只属于它的三页记忆，再问「你叫什么」。",
    wow: "喂对出生纸的瞬间，它想起自己的名字。",
    hook: "那页记忆有落款。被水泡花了。只剩一个字：回。",
    cutscene: [
      { caption: "坏消息。伙伴连名字都忘了。", scene: "tear" },
      { caption: "普通资料，救不了它。要喂它的专属记忆页。", scene: "album" },
      { caption: "别喂错。错了，它会更糊涂。", scene: "wind" },
    ],
    slots: [
      { id: "trigger", label: "开关", hint: "点一点", accepts: ["trigger-tap"], shadow: "outline", gap: true },
      { id: "persona", label: "它是谁", hint: "角色卡", accepts: ["persona"], shadow: "outline", gap: true },
      { id: "memory", label: "记忆页", hint: "建一页只属于它的记忆", accepts: ["memory"], shadow: "outline", gap: true },
      { id: "feed", label: "专属资料", hint: "金边的才是它的", accepts: ["knowledge"], shadow: "outline", gap: true, capacity: 3 },
      { id: "speech", label: "提问", hint: "问：你叫什么", accepts: ["display-speech"], shadow: "outline" },
    ],
    pack: [
      "persona-cat",
      "persona-dog",
      "persona-rabbit",
      "trigger-tap",
      "memory",
      "speech",
      "know-news",
      "know-joke-card",
      "know-other-map",
    ],
    extraPackLowGrade: [],
    quiz: {
      question: "想让伙伴答得准，要喂？",
      options: [
        { id: "a", label: "对的知识", icon: "memory", correct: true },
        { id: "b", label: "随便什么", icon: "rag" },
        { id: "c", label: "烟花", icon: "firework" },
      ],
      cardIds: ["memory"],
    },
  },
  {
    id: "L5",
    index: 5,
    chapter: 2,
    name: "它有本领了",
    concept: "技能是它自己选的",
    motto: "装了技能牌，自己会安排",
    newBlocks: ["skill"],
    shadow: "S1",
    gapCount: 3,
    firstGapSafe: true,
    allowTrial: true,
    autonomy: 60,
    mission: "自己搭回角色卡和开关，再把画画、算数两张技能牌装上。只说事，看它自己举牌。",
    wow: "你说「画 3 只小猫」，没人告诉它用画画，它自己举起画画牌。",
    hook: "新技能牌背面，有抓痕。抓痕是新的。",
    cutscene: [
      { caption: "彩虹环带。七座桥。桥断了，没人修。", scene: "bridge" },
      { caption: "伙伴不会修桥。给它技能牌。", scene: "equip" },
      { caption: "牌装上，它自己举。你说事，它来选。", scene: "choose" },
    ],
    slots: [
      { id: "trigger", label: "开关", hint: "先放点一点", accepts: ["trigger-tap"], shadow: "hint", gap: true },
      { id: "persona", label: "它是谁", hint: "先放角色卡哦", accepts: ["persona"], shadow: "hint", gap: true },
      { id: "rag", label: "百宝箱", hint: "可以带着箱子", accepts: ["rag"], shadow: "hint" },
      { id: "skills", label: "技能槽", hint: "技能牌装进槽", accepts: ["skill"], shadow: "hint", gap: true, capacity: 2 },
      { id: "speech", label: "说话", hint: "气泡", accepts: ["display-speech"], shadow: "hint" },
    ],
    pack: [
      "persona-cat",
      "persona-dog",
      "persona-rabbit",
      "persona-parrot",
      "trigger-tap",
      "rag",
      "speech",
      "skill-draw",
      "skill-math",
    ],
    quiz: {
      question: "技能牌，谁说了算？",
      options: [
        { id: "a", label: "它自己选", icon: "skill", correct: true },
        { id: "b", label: "我指定", icon: "trigger" },
        { id: "c", label: "百宝箱", icon: "rag" },
      ],
      cardIds: ["skill"],
    },
  },
  {
    id: "L6",
    index: 6,
    chapter: 2,
    name: "暗号行动",
    concept: "喊暗号，本领到",
    motto: "喊暗号，本领到",
    newBlocks: ["voice"],
    shadow: "S1",
    gapCount: 3,
    firstGapSafe: false,
    allowTrial: true,
    autonomy: 70,
    mission: "槽只有三个，技能有四张，你决定带哪个。再设一句暗号。",
    wow: "别人的暗号它一律不理。这是你调教出来的、独一无二的它。",
    hook: "我们喊暗号。灰雾那头，回了同一句。",
    cutscene: [
      { caption: "夜。环带集市。卖艺的桥，还差一块。", scene: "night" },
      { caption: "给它一个暗号。听到暗号，它就开嗓。", scene: "stage" },
      { caption: "槽只有三个。技能有四个。你决定。", scene: "slots" },
    ],
    slots: [
      { id: "persona", label: "它是谁", hint: "角色卡", accepts: ["persona"], shadow: "hint", gap: true },
      { id: "rag", label: "百宝箱", hint: "带着箱子", accepts: ["rag"], shadow: "hint" },
      { id: "feed", label: "集市资料", hint: "喂两张", accepts: ["knowledge"], shadow: "hint", capacity: 2 },
      { id: "skills", label: "技能槽×3", hint: "四张里弃一张", accepts: ["skill"], shadow: "hint", gap: true, capacity: 3 },
      { id: "voice", label: "暗号", hint: "设一句暗号词", accepts: ["trigger-voice"], shadow: "hint", gap: true },
      { id: "trigger", label: "点一点", hint: "也可点它", accepts: ["trigger-tap"], shadow: "hint" },
    ],
    pack: [
      "persona-cat",
      "persona-dog",
      "persona-parrot",
      "rag",
      "know-echo-food",
      "know-echo-song",
      "skill-draw",
      "skill-math",
      "skill-sing",
      "skill-joke",
      "trigger-voice",
      "trigger-tap",
    ],
    quiz: {
      question: "喊暗号，是为了？",
      options: [
        { id: "a", label: "让它开始本领", icon: "voice", correct: true },
        { id: "b", label: "吓走灰雾", icon: "firework" },
        { id: "c", label: "换角色卡", icon: "persona" },
      ],
      cardIds: ["voice"],
    },
  },
  {
    id: "L7",
    index: 7,
    chapter: 2,
    name: "晚会策划师",
    concept: "先查箱，再举牌",
    motto: "先查箱，再举牌",
    newBlocks: ["firework", "combo"],
    shadow: "S1-lite",
    gapCount: 4,
    firstGapSafe: false,
    allowTrial: true,
    autonomy: 85,
    mission: "喂晚会资料、装举牌技能、绑烟花，再自创一个环节。客人问，它自己查、举、放。",
    wow: "NPC 问烟花几点放，它自己翻箱、举牌「八点整」、放烟花。",
    hook: "烟花夜。天上映出一张脸。脸在笑。",
    cutscene: [
      { caption: "今晚，环带晚会。全场伙伴，都要出节目。", scene: "fire" },
      { caption: "你的伙伴，当策划师。客人问，它查，它答。", scene: "queue" },
      { caption: "答得好，放烟花。让全场记住它。", scene: "fire" },
    ],
    checklist: ["喂晚会资料", "装举牌技能", "绑烟花", "自创一个环节"],
    npcs: [
      { name: "贝壳摊主", question: "烟花几点放？", expect: "八点" },
      { name: "月亮饼阿姨", question: "菜单上有什么？", expect: "月亮饼" },
      { name: "合唱队长", question: "今晚有合唱吗？", expect: "合唱" },
    ],
    slots: [
      { id: "persona", label: "它是谁", hint: "", accepts: ["persona"], shadow: "none", gap: true },
      { id: "trigger", label: "开关", hint: "", accepts: ["trigger-tap", "trigger-voice"], shadow: "none", gap: true },
      { id: "rag", label: "百宝箱", hint: "喂晚会资料", accepts: ["rag"], shadow: "none", gap: true },
      { id: "feed", label: "晚会资料", hint: "", accepts: ["knowledge"], shadow: "none", gap: true, capacity: 3 },
      { id: "skills", label: "技能", hint: "装举牌", accepts: ["skill"], shadow: "none", capacity: 3 },
      { id: "show", label: "展示", hint: "绑烟花", accepts: ["display-firework", "display-ribbon", "display-speech"], shadow: "none", capacity: 2 },
    ],
    pack: [
      "persona-cat",
      "persona-dog",
      "persona-parrot",
      "persona-owl",
      "trigger-tap",
      "rag",
      "know-show-list",
      "know-show-time",
      "know-show-menu",
      "skill-answer",
      "skill-sing",
      "skill-draw",
      "skill-math",
      "firework",
      "ribbon",
      "speech",
    ],
    quiz: {
      question: "它举牌前，先干了啥？",
      options: [
        { id: "a", label: "查百宝箱", icon: "combo", correct: true },
        { id: "b", label: "先放烟花", icon: "firework" },
        { id: "c", label: "换角色卡", icon: "persona" },
      ],
      cardIds: ["firework", "combo"],
    },
  },
  {
    id: "L8",
    index: 8,
    chapter: 2,
    name: "星核拼合",
    concept: "完整智能伙伴 2.0",
    motto: "带上它，去见真相",
    newBlocks: ["script"],
    shadow: "S0",
    gapCount: 0,
    firstGapSafe: true,
    allowTrial: true,
    autonomy: 100,
    mission: "独立配置：角色卡 + 百宝箱（≥2 资料）+ ≥2 技能 + 触发器。剧本卡藏在最底层，选装。",
    wow: "舱门开了。里面还有一个笼子。名牌上写着：第二个伙伴。",
    hook: "舱门开了。里面还有一个笼子。名牌上写着：第二个伙伴。灰雾，原来也是星灵。",
    cutscene: [
      { caption: "八颗星核，集齐了。舱门，就要开了。", scene: "ship" },
      { caption: "最后一步。做一件大礼：你的伙伴，2.0 版。", scene: "cape" },
      { caption: "带上它，去见真相。", scene: "door" },
    ],
    slots: [
      { id: "persona", label: "它是谁", hint: "", accepts: ["persona"], shadow: "none", gap: true },
      { id: "trigger", label: "开关", hint: "", accepts: ["trigger-tap", "trigger-voice"], shadow: "none", gap: true },
      { id: "rag", label: "百宝箱", hint: "", accepts: ["rag", "memory"], shadow: "none", gap: true },
      { id: "feed", label: "资料", hint: "", accepts: ["knowledge"], shadow: "none", capacity: 4 },
      { id: "skills", label: "技能", hint: "", accepts: ["skill"], shadow: "none", capacity: 3 },
      { id: "show", label: "展示", hint: "", accepts: ["display-speech", "display-firework", "display-ribbon"], shadow: "none", capacity: 2 },
      { id: "script", label: "剧本", hint: "点问号才展开", accepts: ["script-if"], shadow: "none" },
    ],
    pack: [
      "persona-cat",
      "persona-dog",
      "persona-rabbit",
      "persona-parrot",
      "persona-turtle",
      "persona-owl",
      "trigger-tap",
      "trigger-voice",
      "rag",
      "memory",
      "know-echo-loc",
      "know-echo-song",
      "know-show-time",
      "know-show-menu",
      "skill-draw",
      "skill-math",
      "skill-sing",
      "skill-answer",
      "speech",
      "firework",
      "ribbon",
      "script-if",
    ],
    quiz: {
      question: "口诀大闯关：换张卡，会怎样？",
      options: [
        { id: "a", label: "变个它", icon: "persona", correct: true },
        { id: "b", label: "放烟花", icon: "firework" },
        { id: "c", label: "喂资料", icon: "rag" },
      ],
      cardIds: ["script"],
    },
  },
];

export function levelById(id: string): LevelDef | undefined {
  return LEVELS.find((l) => l.id === id);
}

export function nextLevelId(id: string): string | null {
  const i = LEVELS.findIndex((l) => l.id === id);
  if (i < 0 || i >= LEVELS.length - 1) return null;
  return LEVELS[i + 1].id;
}
