/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChestRouteImport } from './routes/chest'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as FreeRouteImport } from './routes/free'
import { Route as MapRouteImport } from './routes/map'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as LevelLevelIdRouteImport } from './routes/level.$levelId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChestRoute = ChestRouteImport.update({
  id: '/chest',
  path: '/chest',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRoute = FreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const LevelLevelIdRoute = LevelLevelIdRouteImport.update({
  id: '/level/$levelId',
  path: '/level/$levelId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chest': typeof ChestRoute
  '/codex': typeof CodexRoute
  '/free': typeof FreeRoute
  '/map': typeof MapRoute
  '/onboard': typeof OnboardRoute
  '/parent': typeof ParentRoute
  '/teacher': typeof TeacherRoute
  '/level/$levelId': typeof LevelLevelIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chest': typeof ChestRoute
  '/codex': typeof CodexRoute
  '/free': typeof FreeRoute
  '/map': typeof MapRoute
  '/onboard': typeof OnboardRoute
  '/parent': typeof ParentRoute
  '/teacher': typeof TeacherRoute
  '/level/$levelId': typeof LevelLevelIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chest': typeof ChestRoute
  '/codex': typeof CodexRoute
  '/free': typeof FreeRoute
  '/map': typeof MapRoute
  '/onboard': typeof OnboardRoute
  '/parent': typeof ParentRoute
  '/teacher': typeof TeacherRoute
  '/level/$levelId': typeof LevelLevelIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chest'
    | '/codex'
    | '/free'
    | '/map'
    | '/onboard'
    | '/parent'
    | '/teacher'
    | '/level/$levelId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chest'
    | '/codex'
    | '/free'
    | '/map'
    | '/onboard'
    | '/parent'
    | '/teacher'
    | '/level/$levelId'
  id:
    | '__root__'
    | '/'
    | '/chest'
    | '/codex'
    | '/free'
    | '/map'
    | '/onboard'
    | '/parent'
    | '/teacher'
    | '/level/$levelId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChestRoute: typeof ChestRoute
  CodexRoute: typeof CodexRoute
  FreeRoute: typeof FreeRoute
  MapRoute: typeof MapRoute
  OnboardRoute: typeof OnboardRoute
  ParentRoute: typeof ParentRoute
  TeacherRoute: typeof TeacherRoute
  LevelLevelIdRoute: typeof LevelLevelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chest': {
      id: '/chest'
      path: '/chest'
      fullPath: '/chest'
      preLoaderRoute: typeof ChestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free': {
      id: '/free'
      path: '/free'
      fullPath: '/free'
      preLoaderRoute: typeof FreeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/level/$levelId': {
      id: '/level/$levelId'
      path: '/level/$levelId'
      fullPath: '/level/$levelId'
      preLoaderRoute: typeof LevelLevelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChestRoute: ChestRoute,
  CodexRoute: CodexRoute,
  FreeRoute: FreeRoute,
  MapRoute: MapRoute,
  OnboardRoute: OnboardRoute,
  ParentRoute: ParentRoute,
  TeacherRoute: TeacherRoute,
  LevelLevelIdRoute: LevelLevelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
